import "../../../test/guard.mjs";
import "./privacy-fixture.mjs";
import assert from "node:assert/strict";
import fs from "node:fs";
import { spawn } from "node:child_process";
import { syncBuiltinESMExports } from "node:module";
import { tmpdir } from "node:os";
import { join, dirname, resolve } from "node:path";
import { mkdtemp, mkdir, readFile, writeFile, readdir, rm, rename, cp, stat } from "node:fs/promises";
import { createHash, randomUUID } from "node:crypto";
import { startService } from "../src/server.ts";
import { Sync, FolderTransport, recoverSync } from "../src/sync.ts";
import { connect } from "../../client/dist/index.js";
import { main } from "../../cli/src/main.ts";
import { newEntry, encrypt, encryptJson, decrypt, decryptJson, unlock, sealSync, openSync, syncPatterns, SYNC_PACKAGE_CAP, SYNC_BLOB_CAP, VaultMemory } from "vault-core";
const parent = resolve(tmpdir()), scratch = await mkdtemp(join(parent, "service-sync-")), folder = join(scratch, "shared"), services = [], clients = [], password = "Synthetic sync master password", nextPassword = "Synthetic next master password", hidden = [], previousHome = process.env.VAULT_HOME, previousLocale = process.env.LC_ALL;
let checks = 0, stage = "all entry kinds", now = Date.now();
const regression = count => { checks += count; };
const tokens = () => { let token; return { async get() { return token; }, async set(value) { token = value; } }; };
const make = async name => { const home = join(scratch, name), service = await startService({ home, now: () => now, idleMs: 1e12, presenceMs: 1e12 }); services.push(service); const api = await connect({ home, app: { id: "vault-app", name: "Synthetic sync app", kind: "cosmic" }, tokens: tokens() }); clients.push(api); return { home, service, api }; };
const reject = (run, code) => assert.rejects(run, error => error.code === code);
async function files(root) { const result = []; for (const item of await readdir(root, { withFileTypes: true })) { const path = join(root, item.name); if (item.isDirectory()) result.push(...await files(path)); else result.push(path); } return result; }
const state = async v => JSON.parse(await readFile(join(v.home, "sync", "state.json"), "utf8"));
const key = v => v.service.vault.memory.get(v.service.vault.memory.ticket());
const storeHash = async v => { const paths = (await files(join(v.home, "store"))).sort(), hash = createHash("sha256"); for (const path of paths) hash.update(await readFile(path)); return hash.digest("hex"); };
const equal = async (a, b) => { const rows = async v => (await v.api.entries.list()).map(row => row.entry).sort((a, b) => a.id.localeCompare(b.id)); assert.deepEqual(await rows(a), await rows(b)); checks++; };
const sync = async v => { now++; await v.api.sync.now(); };
async function fingerprints(root) { const result = {}; for (const path of (await files(root)).sort()) { const info = await stat(path, { bigint: true }); result[path.slice(root.length)] = { ino: info.ino, mtime: info.mtimeNs }; } return result; }
const rewritten = (before, after) => Object.keys(after).filter(name => !before[name] || before[name].ino !== after[name].ino || before[name].mtime !== after[name].mtime);
async function pendingSnapshot(v, header) { const path = join(v.home, "sync", "outbox", header.index, "snapshot"), { parts } = JSON.parse(await readFile(join(path, "parts.json"), "utf8")), publications = []; for (let part = 0; part < parts; part++) { const payload = await decryptJson(key(v), JSON.parse(await readFile(join(path, `${part}.json`), "utf8")), `sync-local:${header.datasetId}:${header.index}:${part}`); if (payload.section === "publications") for (const item of payload.items) { publications[item.publication] ??= { path: item.path, bytes: "" }; publications[item.publication].bytes += item.bytes; } } return { publications }; }
try {
  stage = "idle and single-entry write measurement";
  const measured = await make("measured"), measuredPeer = await make("measured-peer"), measuredFolder = join(scratch, "measured-shared"), measuredEntries = [];
  await measured.api.create(password);
  const measuredChunkId = randomUUID(), measuredChunk = Buffer.from("synthetic-measured-attachment"); await measured.service.vault.store.putChunk(measuredChunkId, await encrypt(key(measured), Uint8Array.from(measuredChunk), `chunk:${measuredChunkId}`));
  for (let i = 0; i < 300; i++) { const entry = newEntry("login"); entry.title = `synthetic-measured-${i}`; if (i === 299) entry.files = [{ id: randomUUID(), name: "synthetic-measured-file", type: "application/octet-stream", size: measuredChunk.length, chunks: [measuredChunkId] }]; measuredEntries.push(entry); const sealed = await encryptJson(key(measured), entry, `entry:${entry.id}`); await writeFile(join(measured.home, "store", `entry-${entry.id}.json`), JSON.stringify({ version: 1, value: { id: entry.id, sealed, chunks: entry.files.flatMap(file => file.chunks) } })); } measuredChunk.fill(0);
  await mkdir(join(measured.home, "sync", "outbox", randomUUID(), "snapshot"), { recursive: true });
  await measured.service.sync.setup(measuredFolder); await measuredPeer.service.sync.join(measuredFolder, password, false);
  assert.deepEqual(await readdir(join(measured.home, "sync", "outbox")), []); regression(1);
  const measuredStore = join(measured.home, "store"), measuredIndex = join(measured.home, "sync", "index"), measuredKept = join(measured.home, "sync", "kept"), storeInode = (await stat(measuredStore, { bigint: true })).ino, idleFiles = await fingerprints(measuredStore), idleIndexFiles = await fingerprints(measuredIndex), idleIndexInfo = await stat(measuredIndex, { bigint: true }), idleKeptFiles = await fingerprints(measuredKept), idleHeader = await state(measured);
  const measurementRead = FolderTransport.prototype.read, reads = [];
  const measurementChunkRead = measured.service.vault.store.getChunk; let idleChunkReads = 0;
  measured.service.vault.store.getChunk = async function (...args) { idleChunkReads++; return measurementChunkRead.apply(this, args); };
  FolderTransport.prototype.read = async function (...args) { reads.push(args[0]); return measurementRead.apply(this, args); };
  try { now++; await measured.service.sync.pulse(); } finally { FolderTransport.prototype.read = measurementRead; measured.service.vault.store.getChunk = measurementChunkRead; }
  assert.equal(idleChunkReads, 0); regression(1);
  assert.equal((await stat(measuredStore, { bigint: true })).ino, storeInode); assert.deepEqual(await fingerprints(measuredStore), idleFiles); assert.deepEqual(await fingerprints(measuredIndex), idleIndexFiles); assert.equal((await stat(measuredIndex, { bigint: true })).ino, idleIndexInfo.ino); assert.equal((await stat(measuredIndex, { bigint: true })).mtimeNs, idleIndexInfo.mtimeNs); assert.deepEqual(await fingerprints(measuredKept), idleKeptFiles); assert.equal((await state(measured)).index, idleHeader.index); assert.equal((await state(measured)).lastSynced, new Date(now).toISOString()); assert.deepEqual(await readdir(join(measured.home, "sync", "outbox")), []); assert.deepEqual(reads, []); regression(10);
  const editMeasured = async (entry, note) => { entry.note = note; const row = (await measured.service.vault.store.entries()).find(row => row.id === entry.id); await measured.service.vault.store.save(entry.id, await encryptJson(key(measured), entry, `entry:${entry.id}`), row.version, []); };
  await editMeasured(measuredEntries[0], "synthetic-one-edited-entry"); const localAfterEdit = await fingerprints(measuredStore), peerBeforeEdit = await fingerprints(join(measuredPeer.home, "store")), ownPackages = new Set((await files(measuredFolder)).filter(path => /[\\/](batches|checkpoints)[\\/]/.test(path)).map(path => path.slice(join(measuredFolder, "Vault Sync", idleHeader.datasetId).length + 1).replaceAll("\\", "/"))); reads.length = 0;
  FolderTransport.prototype.read = async function (...args) { reads.push(args[0]); return measurementRead.apply(this, args); };
  try { now++; await measured.service.sync.pulse(); } finally { FolderTransport.prototype.read = measurementRead; }
  assert.deepEqual(rewritten(idleFiles, await fingerprints(measuredStore)), [`${process.platform === "win32" ? "\\" : "/"}entry-${measuredEntries[0].id}.json`]); assert.deepEqual(await fingerprints(measuredStore), localAfterEdit); assert.equal(reads.some(path => ownPackages.has(path)), false); regression(3);
  await measuredPeer.service.sync.pulse(); assert.deepEqual(rewritten(peerBeforeEdit, await fingerprints(join(measuredPeer.home, "store"))), [`${process.platform === "win32" ? "\\" : "/"}entry-${measuredEntries[0].id}.json`]); await equal(measured, measuredPeer); regression(1);
  stage = "unfinished local outbox writes";
  for (const kind of ["no-header", "partial-header", "no-manifest", "partial-manifest", "missing-part"]) { const header = { ...await state(measured), index: randomUUID() }, path = join(measured.home, "sync", "outbox", header.index); await mkdir(join(path, "snapshot"), { recursive: true }); await writeFile(join(path, "snapshot", "0.json"), "{}"); if (kind === "partial-header") await writeFile(join(path, "state.json"), '{"format":'); else if (kind !== "no-header") await writeFile(join(path, "state.json"), JSON.stringify(header)); if (kind === "partial-manifest") await writeFile(join(path, "snapshot", "parts.json"), '{"parts":'); if (kind === "missing-part") { await rm(join(path, "snapshot", "0.json")); await writeFile(join(path, "snapshot", "parts.json"), '{"parts":1}'); } }
  now++; await measured.service.sync.pulse(); assert.deepEqual(await readdir(join(measured.home, "sync", "outbox")), []); assert.equal((await measured.service.sync.status()).failure, null); assert.deepEqual(await fingerprints(measuredStore), localAfterEdit); regression(3);
  stage = "actionable folder and local failures";
  const measurementList = FolderTransport.prototype.list;
  for (const [errno, cause] of [["ENOENT", "sync_folder_missing"], ["EPERM", "sync_permission_denied"], ["EACCES", "sync_access_denied"], ["EBUSY", "sync_busy"]]) {
    FolderTransport.prototype.list = async function () { throw Object.assign(new Error("synthetic_file_failure"), { code: errno }); };
    try { await reject(() => measured.service.sync.pulse(), cause); } finally { FolderTransport.prototype.list = measurementList; }
    assert.equal((await measured.service.sync.status()).failure.cause, cause); regression(2);
    const originalOpen = fs.promises.open;
    fs.promises.open = async (path, ...args) => { if (dirname(path) === measuredStore && args[0] === "wx") throw Object.assign(new Error("synthetic_local_failure"), { code: errno }); return originalOpen(path, ...args); }; syncBuiltinESMExports();
    try { await reject(() => measured.service.sync.pulse(), cause); } finally { fs.promises.open = originalOpen; syncBuiltinESMExports(); }
    assert.equal((await measured.service.sync.status()).failure.cause, cause); regression(2);
    const originalMkdir = fs.mkdirSync, localSync = new Sync(measured.home, measured.service.vault, () => now, async () => {}, () => {}); await localSync.load();
    fs.mkdirSync = (path, ...args) => { if (path === join(measured.home, "sync")) throw Object.assign(new Error("synthetic_permission_failure"), { code: errno }); return originalMkdir(path, ...args); };
    try { await reject(() => localSync.pulse(), cause); } finally { fs.mkdirSync = originalMkdir; }
    assert.equal((await localSync.status()).failure.cause, cause); regression(2);
  }
  await rename(join(measuredFolder, "Vault Sync", idleHeader.datasetId), join(measuredFolder, "missing-dataset"));
  try { await reject(() => measured.service.sync.pulse(), "sync_folder_missing"); assert.equal((await measured.service.sync.status()).failure.cause, "sync_folder_missing"); regression(2); } finally { await rename(join(measuredFolder, "missing-dataset"), join(measuredFolder, "Vault Sync", idleHeader.datasetId)); }
  await measured.service.sync.pulse(); assert.equal((await measured.service.sync.status()).failure, null); regression(1);
  stage = "hard-linked stage process crashes";
  for (const point of ["stage", "swap", "state"]) {
    const beforeCrash = await fingerprints(join(measuredPeer.home, "store")), beforeHash = await storeHash(measuredPeer), beforeHeader = await state(measuredPeer), target = measuredEntries[1];
    await editMeasured(target, `synthetic-crash-${point}`); await measured.service.sync.pulse(); await measuredPeer.api.close(); await measuredPeer.service.shutdown();
    const program = `
      let step = 'imports'; try {
      await import('./test/guard.mjs'); await import('./packages/service/test/privacy-fixture.mjs');
      const fs = (await import('node:fs')).default, { join, dirname } = await import('node:path');
      const { startService } = await import('./packages/service/src/server.ts'), { unlock } = await import('vault-core');
      const home = process.env.SYNC_CRASH_HOME, point = process.env.SYNC_CRASH_POINT, entryId = process.env.SYNC_CRASH_ENTRY;
      step = 'start'; const service = await startService({ home, now: () => 0, idleMs: 1e12, presenceMs: 1e12 });
      step = 'unlock';
      const opened = await unlock((await service.vault.store.envelope()).state, 'Synthetic sync master password'); opened.bytes.fill(0); service.vault.memory.open(opened.key, service.vault.memory.ticket());
      const rename = fs.renameSync, renameAsync = fs.promises.rename, { syncBuiltinESMExports } = await import('node:module');
      const crash = (from, to) => { const outbox = join(home, 'sync', 'outbox');
        if (point === 'stage' && dirname(to).startsWith(outbox) && to.endsWith('entry-' + entryId + '.json') || point === 'swap' && from.startsWith(outbox) && to === join(home, 'store') || point === 'state' && to === join(home, 'sync', 'state.json')) process.exit(86);
      };
      fs.renameSync = (from, to) => { rename(from, to); crash(from, to); };
      fs.promises.rename = async (from, to) => { await renameAsync(from, to); crash(from, to); }; syncBuiltinESMExports();
      step = 'pulse'; await service.sync.pulse(); process.exit(87);
      } catch (error) { process.stdout.write(JSON.stringify({ step, code: /^[A-Z_]+$/.test(error?.code ?? '') ? error.code : 'operation' })); process.exit(88); }
    `;
    let diagnostic = "";
    const exit = await new Promise((done, fail) => { const child = spawn(process.execPath, ["--input-type=module", "-e", program], { cwd: new URL("../../../", import.meta.url), env: { ...process.env, SYNC_CRASH_HOME: measuredPeer.home, SYNC_CRASH_POINT: point, SYNC_CRASH_ENTRY: target.id }, stdio: ["ignore", "pipe", "ignore"], windowsHide: true, signal: AbortSignal.timeout(60000) }); child.stdout.on("data", bytes => { diagnostic += bytes; }); child.once("error", fail); child.once("exit", done); }); if (exit !== 86) console.error(`Vault sync crash test ${point}: exit ${exit}, ${diagnostic}.`); assert.equal(exit, 86); regression(1);
    measuredPeer.service = await startService({ home: measuredPeer.home, now: () => now, idleMs: 1e12, presenceMs: 1e12 }); services.push(measuredPeer.service);
    if (point !== "state") { assert.equal(await storeHash(measuredPeer), beforeHash); assert.deepEqual(await fingerprints(join(measuredPeer.home, "store")), beforeCrash); assert.equal((await state(measuredPeer)).index, beforeHeader.index); regression(3); }
    const opened = await unlock((await measuredPeer.service.vault.store.envelope()).state, password); opened.bytes.fill(0); measuredPeer.service.vault.memory.open(opened.key, measuredPeer.service.vault.memory.ticket());
    await measuredPeer.service.sync.pulse(); measuredPeer.api = await connect({ home: measuredPeer.home, app: { id: "vault-app", name: "Synthetic sync app", kind: "cosmic" }, tokens: tokens() }); clients.push(measuredPeer.api);
    assert.equal((await measuredPeer.api.entries.get(target.id)).entry.note === target.note, true); assert.deepEqual(rewritten(beforeCrash, await fingerprints(join(measuredPeer.home, "store"))), [`${process.platform === "win32" ? "\\" : "/"}entry-${target.id}.json`]); assert.deepEqual(await readdir(join(measuredPeer.home, "sync", "outbox")), []); await equal(measured, measuredPeer); regression(3);
  }
  await measured.api.close(); await measured.service.shutdown(); await measuredPeer.api.close(); await measuredPeer.service.shutdown();
  stage = "all entry kinds";
  const a = await make("a"), b = await make("b"), kit = await a.api.create(password), entries = [];
  for (const kind of ["login", "card", "doc", "note", "key", "custom", "env"]) { const entry = newEntry(kind); entry.title = `synthetic-private-title-${kind}`; entry.note = `synthetic-private-note-${kind}`; entry.fields = [{ id: `SYNTHETIC_${kind.toUpperCase()}_FIELD`, name: `synthetic-private-field-name-${kind}`, value: `synthetic-private-value-${kind}`, secret: true }]; hidden.push(entry.title, entry.note, entry.fields[0].id, entry.fields[0].name, entry.fields[0].value); entries.push(entry); }
  const chunkId = randomUUID(), attached = Buffer.from("synthetic-private-attachment-bytes"), document = entries.find(entry => entry.kind === "doc"); document.files = [{ id: randomUUID(), name: "synthetic-private-filename", type: "application/octet-stream", size: attached.length, chunks: [chunkId] }]; hidden.push(document.files[0].name, attached.toString(), password, kit.recovery);
  await a.service.vault.store.putChunk(chunkId, await encrypt(key(a), Uint8Array.from(attached), `chunk:${chunkId}`)); for (const entry of entries) await a.api.entries.save(entry, 0);
  const started = performance.now(); await a.api.sync.setup(folder); console.log(`Vault sync initial pulse: ${((performance.now() - started) / 1000).toFixed(3)} s.`);
  await b.api.sync.join(folder, { password }); await equal(a, b);
  const bytes = await decrypt(key(b), await b.service.vault.store.getChunk(chunkId), `chunk:${chunkId}`); assert.equal(Buffer.from(bytes).equals(attached), true); bytes.fill(0); attached.fill(0); checks++;
  const c = await make("c"), d = await make("d"); await c.api.sync.join(folder, { recovery: kit.recovery }); await equal(a, c);
  const checkpointRead = FolderTransport.prototype.read; let checkpointReads = 0, batchReads = 0;
  FolderTransport.prototype.read = async function (...args) { if (args[0].includes("/checkpoints/")) checkpointReads++; if (args[0].includes("/batches/")) batchReads++; return checkpointRead.apply(this, args); };
  try { await d.api.sync.join(folder, { password }); } finally { FolderTransport.prototype.read = checkpointRead; } await equal(a, d); assert.equal(checkpointReads > 0, true); assert.equal(batchReads, 0); checks += 2;
  const joinedState = await state(d), checkpointNames = (await files(folder)).filter(path => path.includes("checkpoints")); assert.equal(checkpointNames.length >= 4, true); assert.equal(joinedState.sequence, 0); checks += 2; await c.api.close(); await c.service.shutdown(); await d.api.close(); await d.service.shutdown();
  stage = "join authentication backoff";
  const wrong = await make("wrong"); await reject(() => wrong.api.sync.join(folder, { password: "Synthetic wrong master password" }), "locked"); await reject(() => wrong.api.sync.join(folder, { password }), "limited"); assert.equal((await wrong.api.status()).created, false); now += 1000;
  await reject(() => wrong.api.sync.join(folder, { recovery: "AAAA-AAAA-AAAA-AAAA-AAAA-AAAA" }), "locked"); await reject(() => wrong.api.sync.join(folder, { recovery: kit.recovery }), "limited"); assert.equal((await wrong.api.status()).created, false); now += 2000; await wrong.api.sync.join(folder, { recovery: kit.recovery }); checks += 6; await wrong.api.close(); await wrong.service.shutdown();
  const occupied = await make("occupied"); await occupied.api.create(password); await reject(() => occupied.api.sync.join(folder, { password }), "sync_existing"); checks++; await occupied.api.close(); await occupied.service.shutdown();
  stage = "concurrent edits, restore and dismiss";
  const login = entries[0], change = async (v, entryId, value) => { hidden.push(value); const row = await v.api.entries.get(entryId); row.entry.note = value; row.entry.updatedAt = new Date(now).toISOString(); await v.api.entries.save(row.entry, row.version); };
  await change(a, login.id, "synthetic-older-edit"); await change(b, login.id, "synthetic-newer-edit"); await sync(a); await sync(b); await sync(a); await equal(a, b); assert.equal((await a.api.entries.get(login.id)).entry.note === "synthetic-newer-edit", true);
  const conflictsA = await a.api.sync.conflicts(), conflictsB = await b.api.sync.conflicts(); assert.equal(conflictsA.length, 1); assert.equal(conflictsB.length, 1); assert.equal(conflictsA[0].id, conflictsB[0].id); await a.api.sync.restore(conflictsA[0].id); await sync(a); await sync(b); await equal(a, b); assert.equal((await b.api.entries.get(login.id)).entry.note === "synthetic-older-edit", true); await b.api.sync.dismiss(conflictsB[0].id); assert.equal((await b.api.sync.conflicts()).length, 0); checks += 7;
  stage = "delete against edit";
  const note = entries.find(entry => entry.kind === "note"), noteRow = await a.api.entries.get(note.id); await a.api.entries.remove(note.id, noteRow.version); await change(b, note.id, "synthetic-edit-beats-delete"); await sync(a); await sync(b); await sync(a); await equal(a, b); assert.equal((await a.api.entries.get(note.id)).entry.note === "synthetic-edit-beats-delete", true); assert.equal((await a.api.sync.conflicts()).some(row => row.deleted), true); checks += 2;
  stage = "same-project environments";
  const envA = newEntry("env"), envB = newEntry("env"); envA.title = envB.title = "synthetic-concurrent-project"; envA.fields = [{ id: "SYNTHETIC_ENV", name: "synthetic-environment-name", value: "synthetic-env-older", secret: true }]; envB.fields = [{ ...envA.fields[0], value: "synthetic-env-newer" }]; hidden.push(envA.title, envA.fields[0].id, envA.fields[0].name, envA.fields[0].value, envB.fields[0].value);
  await a.api.entries.save(envA, 0); await b.api.entries.save(envB, 0); await sync(a); await sync(b); await sync(a); await equal(a, b); assert.equal((await a.api.entries.list()).filter(row => row.entry.kind === "env" && row.entry.title === envA.title).length, 1); assert.equal((await a.api.sync.conflicts()).some(row => row.kind === "env" && row.title === envA.title), true); checks += 2;
  stage = "recovery propagation";
  const recovery = await a.api.recover(kit.recovery, nextPassword); hidden.push(nextPassword, recovery.recovery); await sync(a); await sync(b); await b.api.lock(); await reject(() => b.api.unlock(password), "locked"); now += 1000; await b.api.unlock(nextPassword); await equal(a, b); const later = await make("later"); await later.api.sync.join(folder, { recovery: recovery.recovery }); await equal(a, later); const masterLater = await make("master-later"); await masterLater.api.sync.join(folder, { password: nextPassword }); await equal(a, masterLater); checks++; await later.api.close(); await later.service.shutdown(); await masterLater.api.close(); await masterLater.service.shutdown();
  stage = "incoming package refusal and exact names";
  await change(a, login.id, "synthetic-after-refusal"); await sync(a); const config = await state(a), batchFolder = join(folder, "Vault Sync", config.datasetId, "writers", config.deviceId, config.generationId, "batches"), names = (await readdir(batchFolder)).sort((a, b) => Number(a.split("-")[0]) - Number(b.split("-")[0])), name = names.at(-1), batchPath = join(batchFolder, name), original = await readFile(batchPath, "utf8"), before = await storeHash(b), beforeState = await readFile(join(b.home, "sync", "state.json"), "utf8");
  const tampered = JSON.parse(original); tampered.sealed.data = `${tampered.sealed.data[0] === "A" ? "B" : "A"}${tampered.sealed.data.slice(1)}`;
  for (const invalid of [JSON.stringify(tampered), original.slice(0, -12), "x".repeat(SYNC_PACKAGE_CAP + 1), original.replace('"version":1', '"version":2')]) { await writeFile(batchPath, invalid); await assert.rejects(() => b.api.sync.now()); assert.equal(await storeHash(b), before); assert.equal(await readFile(join(b.home, "sync", "state.json"), "utf8"), beforeState); checks += 3; }
  const match = /^(\d+)-(.+)\.vsync$/.exec(name), address = { datasetId: config.datasetId, deviceId: config.deviceId, generationId: config.generationId, type: "batch", sequence: Number(match[1]), packageId: match[2] }, payload = await openSync(key(a), address, original), foreign = await sealSync(key(a), { ...address, datasetId: randomUUID() }, payload);
  await writeFile(batchPath, foreign); await reject(() => b.api.sync.now(), "invalid"); assert.equal(await storeHash(b), before); checks += 2;
  await writeFile(batchPath, await sealSync(key(a), { ...address, deviceId: randomUUID() }, payload)); await reject(() => b.api.sync.now(), "invalid"); assert.equal(await storeHash(b), before); checks += 2;
  await writeFile(batchPath, original); await rename(batchPath, batchPath.replace(".vsync", "-SCOUT.vsync")); await writeFile(`${batchPath}.partial`, original.slice(0, 12)); await writeFile(join(batchFolder, ".partial-download"), original.slice(0, 12)); await sync(b); assert.equal(await storeHash(b), before); checks++;
  await rename(batchPath.replace(".vsync", "-SCOUT.vsync"), batchPath); await sync(b); await equal(a, b);
  stage = "sequence gap";
  await change(a, login.id, "synthetic-gap-one"); await sync(a); const gapState = await state(a), gapName = (await readdir(batchFolder)).find(name => name.startsWith(`${gapState.sequence}-`)), gapPath = join(batchFolder, gapName), gapBytes = await readFile(gapPath, "utf8"); await rename(gapPath, `${gapPath}.partial`); await change(a, login.id, "synthetic-gap-two"); await sync(a); const gapHash = await storeHash(b), applied = (await state(b)).index;
  await reject(() => b.api.sync.now(), "sync_gap"); assert.equal(await storeHash(b), gapHash); assert.equal((await state(b)).index, applied); await writeFile(gapPath, gapBytes); await sync(b); await equal(a, b); checks += 3;
  stage = "sealed outbox crash replay";
  await change(a, login.id, "synthetic-crash-replay"); const originalWrite = FolderTransport.prototype.write;
  FolderTransport.prototype.write = async function () { throw new Error("synthetic_transport_failure"); };
  try { await reject(() => a.api.sync.now(), "sync_unavailable"); } finally { FolderTransport.prototype.write = originalWrite; }
  const outboxId = (await readdir(join(a.home, "sync", "outbox")))[0], header = JSON.parse(await readFile(join(a.home, "sync", "outbox", outboxId, "state.json"), "utf8")), snapshot = await pendingSnapshot(a, header), pendingBatch = snapshot.publications.find(item => item.path.includes("/batches/")); assert.equal(!!pendingBatch, true);
  await change(a, login.id, "synthetic-write-after-crash"); await a.api.close(); await a.service.shutdown(); a.service = await startService({ home: a.home, now: () => now, idleMs: 1e12, presenceMs: 1e12 }); services.push(a.service); a.api = await connect({ home: a.home, app: { id: "vault-app", name: "Synthetic sync app", kind: "cosmic" }, tokens: tokens() }); clients.push(a.api); await a.api.unlock(nextPassword); await sync(a); assert.equal(await readFile(join(folder, "Vault Sync", config.datasetId, ...pendingBatch.path.split("/")), "utf8"), pendingBatch.bytes); assert.deepEqual(await readdir(join(a.home, "sync", "outbox")), []); assert.equal((await a.api.entries.get(login.id)).entry.note === "synthetic-write-after-crash", true); await sync(b); await equal(a, b); checks += 4;
  stage = "lock during read and during publishing";
  await change(a, login.id, "synthetic-mid-pulse-lock"); await sync(a); const lockState = await readFile(join(b.home, "sync", "state.json"), "utf8"), lockHash = await storeHash(b), originalRead = FolderTransport.prototype.read; let locked = false;
  FolderTransport.prototype.read = async function (...args) { const result = await originalRead.apply(this, args); if (!locked && args[0].includes("/batches/")) { locked = true; b.service.vault.memory.lock(); } return result; };
  try { await reject(() => b.api.sync.now(), "locked"); } finally { FolderTransport.prototype.read = originalRead; }
  assert.equal(locked, true); assert.equal(await storeHash(b), lockHash); assert.equal(await readFile(join(b.home, "sync", "state.json"), "utf8"), lockState); await b.api.unlock(nextPassword); await sync(b); await equal(a, b); checks += 3;
  await change(a, login.id, "synthetic-lock-during-publish"); const publishState = await readFile(join(a.home, "sync", "state.json"), "utf8"), publishHash = await storeHash(a), publishedBefore = (await files(folder)).sort(); locked = false;
  FolderTransport.prototype.write = async function (...args) { const result = await originalWrite.apply(this, args); if (!locked && args[0].includes("/batches/")) { locked = true; a.service.vault.memory.lock(); } return result; };
  try { await reject(() => a.api.sync.now(), "locked"); } finally { FolderTransport.prototype.write = originalWrite; }
  assert.equal(locked, true); assert.equal(await storeHash(a), publishHash); assert.equal(await readFile(join(a.home, "sync", "state.json"), "utf8"), publishState); assert.deepEqual((await files(folder)).sort(), publishedBefore); assert.deepEqual(await readdir(join(a.home, "sync", "outbox")), []); await a.api.unlock(nextPassword); await sync(a); await sync(b); await equal(a, b); checks += 5;
  stage = "blob size and authentication";
  await change(a, document.id, "synthetic-changed-document"); await sync(a); const blobPath = join(folder, "Vault Sync", config.datasetId, "writers", config.deviceId, config.generationId, "blobs", `${chunkId}.vsync`), originalBlob = await readFile(blobPath, "utf8"), blobHash = await storeHash(b);
  for (const invalid of ["x".repeat(SYNC_BLOB_CAP + 1), originalBlob.slice(0, -8)]) { await writeFile(blobPath, invalid); await assert.rejects(() => b.api.sync.now()); assert.equal(await storeHash(b), blobHash); checks += 2; } await writeFile(blobPath, originalBlob); await sync(b); await equal(a, b);
  stage = "index reconstruction and copied generation";
  const rebuilding = await state(b), conflictsBefore = (await b.api.sync.conflicts()).map(row => row.id).sort(), sequenceBefore = rebuilding.sequence;
  await rm(join(b.home, "sync", "index", rebuilding.index), { recursive: true }); await sync(b); await equal(a, b); assert.equal((await state(b)).sequence, sequenceBefore); assert.deepEqual((await b.api.sync.conflicts()).map(row => row.id).sort(), conflictsBefore); checks += 2;
  const copiedHome = join(scratch, "copied"); await cp(a.home, copiedHome, { recursive: true }); assert.equal(dirname(copiedHome), scratch); await rm(join(copiedHome, "run"), { recursive: true }); const copiedService = await startService({ home: copiedHome, now: () => now, idleMs: 1e12, presenceMs: 1e12 }); services.push(copiedService); const copiedApi = await connect({ home: copiedHome, app: { id: "vault-app", name: "Synthetic sync app", kind: "cosmic" }, tokens: tokens() }); clients.push(copiedApi); const copied = { home: copiedHome, service: copiedService, api: copiedApi };
  await copiedApi.unlock(nextPassword); await sync(copied); const copiedState = await state(copied), sourceState = await state(a); assert.notEqual(copiedState.generationId, sourceState.generationId); assert.notEqual(copiedState.deviceId, sourceState.deviceId); await equal(a, copied); checks += 2; await copied.api.close(); await copied.service.shutdown();
  stage = "restored generation and local commit recovery";
  const restoreHeader = await state(b), restoreBackup = join(scratch, "restore-backup"); await cp(join(b.home, "store"), join(restoreBackup, "store"), { recursive: true }); await cp(join(b.home, "sync", "index", restoreHeader.index), join(restoreBackup, "index"), { recursive: true });
  await change(b, login.id, "synthetic-change-after-local-backup"); await sync(b); await sync(a); await b.api.close(); await b.service.shutdown(); assert.equal(dirname(b.home), scratch); await rm(join(b.home, "store"), { recursive: true }); await cp(join(restoreBackup, "store"), join(b.home, "store"), { recursive: true }); await rm(join(b.home, "sync", "index"), { recursive: true }); await cp(join(restoreBackup, "index"), join(b.home, "sync", "index", restoreHeader.index), { recursive: true }); await writeFile(join(b.home, "sync", "state.json"), JSON.stringify(restoreHeader));
  b.service = await startService({ home: b.home, now: () => now, idleMs: 1e12, presenceMs: 1e12 }); services.push(b.service); b.api = await connect({ home: b.home, app: { id: "vault-app", name: "Synthetic sync app", kind: "cosmic" }, tokens: tokens() }); clients.push(b.api); await b.api.unlock(nextPassword); await sync(b); assert.notEqual((await state(b)).generationId, restoreHeader.generationId); assert.equal((await b.api.entries.get(login.id)).entry.note === "synthetic-change-after-local-backup", true); await equal(a, b); checks += 2;
  const journalHome = join(scratch, "journal"), journalRoot = join(journalHome, "sync"), journalHeader = await state(a), nextHeader = { ...journalHeader, index: randomUUID() }; await mkdir(journalRoot, { recursive: true }); await cp(join(a.home, "store"), join(journalHome, "store"), { recursive: true }); const journalHash = await storeHash({ home: journalHome });
  await writeFile(join(journalRoot, "state.json"), JSON.stringify(journalHeader)); await writeFile(join(journalRoot, "commit.json"), JSON.stringify({ next: nextHeader, previous: journalHeader })); await rename(join(journalHome, "store"), join(journalRoot, "previous")); await mkdir(join(journalHome, "store")); recoverSync(journalHome); assert.equal(await storeHash({ home: journalHome }), journalHash); assert.equal(JSON.parse(await readFile(join(journalRoot, "state.json"), "utf8")).index, journalHeader.index); await assert.rejects(() => readFile(join(journalRoot, "commit.json"))); checks += 3;
  await cp(join(journalHome, "store"), join(journalRoot, "previous"), { recursive: true }); await writeFile(join(journalRoot, "state.json"), JSON.stringify(nextHeader)); await writeFile(join(journalRoot, "commit.json"), JSON.stringify({ next: nextHeader, previous: journalHeader })); recoverSync(journalHome); assert.equal(await storeHash({ home: journalHome }), journalHash); assert.equal(JSON.parse(await readFile(join(journalRoot, "state.json"), "utf8")).index, nextHeader.index); await assert.rejects(() => readdir(join(journalRoot, "previous"))); checks += 3;
  stage = "writer caps and unchanged local writes on refusal";
  const datasetRoot = join(folder, "Vault Sync", config.datasetId), fakeDevices = [];
  for (let i = 0; i < 65; i++) { const device = randomUUID(); fakeDevices.push(device); await mkdir(join(datasetRoot, "writers", device, randomUUID()), { recursive: true }); }
  const cappedHash = await storeHash(b), cappedState = (await state(b)).index; await reject(() => b.api.sync.now(), "limited"); assert.equal(await storeHash(b), cappedHash); assert.equal((await state(b)).index, cappedState); assert.equal((await b.api.sync.status()).failure.cause, "limited"); checks += 3;
  for (const device of fakeDevices) await rm(join(datasetRoot, "writers", device), { recursive: true }); await sync(b);
  stage = "checkpoints, parts and thirty-day compaction";
  const addRows = async (count, dense = false) => { for (let i = 0; i < count; i++) { const entry = newEntry("note"); entry.title = `synthetic-checkpoint-title-${dense}-${i}`; hidden.push(entry.title); if (dense && i < 30) { entry.note = "synthetic-long-note-".repeat(1600); entry.fields = Array.from({ length: 5 }, (_, field) => ({ id: `SYNTHETIC_DENSE_${field}`, name: "synthetic-dense-field-name", value: "synthetic-long-value-".repeat(1500), secret: true })); } if (dense && i < 30) hidden.push(entry.note, ...entry.fields.flatMap(field => [field.id, field.name, field.value])); const sealed = await encryptJson(key(a), entry, `entry:${entry.id}`); await writeFile(join(a.home, "store", `entry-${entry.id}.json`), JSON.stringify({ version: 1, value: { id: entry.id, sealed, chunks: [] } }), { mode: 0o600 }); } };
  await addRows(500, true); const largeStarted = performance.now(); await sync(a); console.log(`Vault sync split checkpoint: ${((performance.now() - largeStarted) / 1000).toFixed(3)} s.`); const checkpointState = await state(a), checkpointRoot = join(datasetRoot, "writers", config.deviceId, config.generationId, "checkpoints"), splitNames = (await readdir(checkpointRoot)).filter(name => name.startsWith(`${checkpointState.sequence}-`)); assert.equal(checkpointState.operations, 0); assert.equal(splitNames.length > 1, true); for (const name of splitNames) assert.equal(Buffer.byteLength(await readFile(join(checkpointRoot, name), "utf8")) < SYNC_PACKAGE_CAP, true); checks += 2;
  const multipart = await make("multipart"); await multipart.api.sync.join(folder, { password: nextPassword }); await equal(a, multipart);
  await addRows(500); now += 31 * 86400000; await sync(a); const compacted = await state(a), remainingBatches = await readdir(batchFolder); assert.equal(remainingBatches.every(name => !syncPatterns.batch.test(name) || Number(name.split("-")[0]) >= compacted.checkpoint), true); assert.equal((await a.api.entries.list()).length > 1000, true); checks += 2;
  await sync(multipart); await equal(a, multipart); console.log("Vault sync checkpoints and compaction passed.");
  stage = "idle time and scheduled queue";
  let clock = 0; const idle = await make("idle"), memory = new VaultMemory(() => clock, 100); idle.service.vault.memory = memory; memory.open(key(a), memory.ticket()); await idle.service.vault.store.create((await a.service.vault.store.envelope()).state); await idle.api.sync.setup(join(scratch, "idle-shared")); clock = 99; await idle.api.sync.now(); clock = 100; assert.throws(() => memory.get(memory.ticket())); checks++;
  let scheduledClock = 0; const scheduledHome = join(scratch, "scheduled"), scheduledService = await startService({ home: scheduledHome, now: () => scheduledClock, idleMs: 1200000, presenceMs: 1200000 }); services.push(scheduledService); const scheduledApi = await connect({ home: scheduledHome, app: { id: "vault-app", name: "Synthetic sync app", kind: "cosmic" }, tokens: tokens() }); clients.push(scheduledApi);
  await scheduledApi.create(password); await scheduledApi.sync.setup(join(scratch, "scheduled-folder")); const scheduledEntry = newEntry("note"); await scheduledApi.entries.save(scheduledEntry, 0);
  const scheduledKey = scheduledService.vault.memory.get(scheduledService.vault.memory.ticket()); await scheduledApi.lock(); assert.equal((await scheduledApi.sync.status()).pending, 1); assert.equal((await scheduledApi.sync.status()).conflicts, 0); scheduledService.vault.memory.open(scheduledKey, scheduledService.vault.memory.ticket()); checks += 2;
  const touch = scheduledService.vault.memory.touch; scheduledService.vault.memory.touch = () => { throw new Error("sync_activity"); };
  try { scheduledClock = 4999; scheduledService.checkSync(); assert.equal((await scheduledApi.sync.status()).pending, 1); scheduledClock = 5000; scheduledService.checkSync(); assert.equal((await scheduledApi.sync.status()).pending, 0); assert.equal((await scheduledApi.sync.status()).lastSynced, new Date(5000).toISOString()); scheduledClock = 64999; scheduledService.checkSync(); assert.equal((await scheduledApi.sync.status()).lastSynced, new Date(5000).toISOString()); scheduledClock = 65000; scheduledService.checkSync(); assert.equal((await scheduledApi.sync.status()).lastSynced, new Date(65000).toISOString()); } finally { scheduledService.vault.memory.touch = touch; } checks += 5;
  await scheduledApi.lock(); scheduledClock = 70000; await scheduledApi.unlock(password); assert.equal((await scheduledApi.sync.status()).lastSynced, new Date(70000).toISOString()); await scheduledApi.close(); await scheduledService.shutdown(); checks++;
  stage = "CLI languages and family consent";
  process.env.VAULT_HOME = a.home; const lines = [], answers = [], io = { isTTY: () => true, async ask() { return answers.shift(); }, write(value) { lines.push(value); }, error(value) { lines.push(value); }, out(value) { lines.push(value); }, err(value) { lines.push(value); } };
  process.env.LC_ALL = "en"; assert.equal(await main(["sync", "status"], io), 0); assert.equal(lines.some(line => line.startsWith("Folder: ")), true); assert.equal(lines.some(line => line.includes("pending changes")), true); checks += 3;
  lines.length = 0; process.env.LC_ALL = "es"; assert.equal(await main(["sync", "status"], io), 0); assert.equal(lines.some(line => line.startsWith("Carpeta: ")), true); assert.equal(lines.some(line => line.includes("cambios pendientes")), true); checks += 3;
  lines.length = 0; process.env.VAULT_HOME = join(scratch, "no-consent"); answers.push("no"); assert.equal(await main(["sync", "setup", join(scratch, "refused")], io), 1); await assert.rejects(() => readdir(process.env.VAULT_HOME)); assert.equal(lines.some(line => line.includes("fortaleza")), true); checks += 3;
  stage = "secret-free folder and local records";
  for (const path of await files(folder)) { const content = await readFile(path, "utf8"); for (const secret of new Set(hidden)) assert.equal(content.includes(secret), false); }
  for (const v of [a, b, c, d]) for (const path of [...await files(join(v.home, "sync")), ...await files(join(v.home, "logs"))]) { const content = await readFile(path, "utf8"); for (const secret of hidden) assert.equal(content.includes(secret), false); } checks += 2;
  stage = "leave isolation";
  await change(b, login.id, "synthetic-before-leave"); FolderTransport.prototype.write = async function (...args) { if (args[0].includes("/batches/")) throw new Error("synthetic_transport_failure"); return originalWrite.apply(this, args); }; try { await reject(() => b.api.sync.now(), "sync_unavailable"); } finally { FolderTransport.prototype.write = originalWrite; } assert.equal((await readdir(join(b.home, "sync", "outbox"))).length, 1); checks++;
  const writerB = await state(b), writerA = await state(a); await b.api.sync.leave(true); await assert.rejects(() => readdir(join(folder, "Vault Sync", writerB.datasetId, "writers", writerB.deviceId))); assert.equal((await readdir(join(folder, "Vault Sync", writerA.datasetId, "writers", writerA.deviceId))).length > 0, true); assert.equal((await b.api.sync.status()).configured, false); checks += 3;
  await assert.rejects(() => readdir(join(b.home, "sync", "outbox"))); assert.equal((await b.api.sync.status()).failure, null); checks += 2;
  console.log(`Vault sync service: ${checks} checks passed.`);
} catch (error) { console.error(`Vault sync service failed at ${stage}: ${error?.code ?? "assertion"}.`); if (error?.stack) console.error(error.stack.split("\n").filter(line => /^\s+at .*sync\.(?:test\.mjs|ts):\d+:\d+/.test(line)).join("\n")); throw new Error("sync service check failed"); }
finally { for (const api of clients) await api.close().catch(() => undefined); for (const service of services) await service.shutdown(); if (previousHome === undefined) delete process.env.VAULT_HOME; else process.env.VAULT_HOME = previousHome; if (previousLocale === undefined) delete process.env.LC_ALL; else process.env.LC_ALL = previousLocale; assert.equal(dirname(scratch), parent); await rm(scratch, { recursive: true, force: true, maxRetries: 10, retryDelay: 10 }); }
